### ISSUE TITLE
How to set last_event_id?

### ISSUE THREAD

**Issue by bezysoftware** [firebase/EventSource-Examples#4]
Hi, in the sample when you are reading the contents of a stream (method handle_stream) you are reading the "id" of the event so you can later supply it to the last_event_id in the header. But when I am trying the streaming api myself, the server never sends the id, therefore I cannot populate the last_event_id.

How can I accomplish this?

**Comment by gsoltis** [comment]
The Firebase Database does not support `last_event_id`. The ruby library for handling event streams supports it, but we don't make use of it.
